name: tests
on:
  pull_request:
    branches:
      - main
    paths:
      - 'UnityProject/Saneject/**'
      - 'RoslynTools/**'
  workflow_dispatch:
      
jobs:
  tests:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unity: [2022.3.12f1, 2022.3.62f3, 6000.0.58f2, 6000.0.63f1, 6000.1.17f1, 6000.2.6f2, 6000.2.15f1, 6000.3.0f1]
    steps:
      - uses: actions/checkout@v4

      - name: EditMode tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: ${{ matrix.unity }}
          testMode: editmode
          projectPath: UnityProject/Saneject
          customParameters: -nographics -assemblyNames Saneject.Tests.Editor
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: "EditMode (${{ matrix.unity }})"
